export const CREATE_TICKETS_EVENT = 'CREATE_TICKETS_EVENT';
export const READ_TICKETS_EVENT = 'READ_TICKETS_EVENT';
export const UPDATE_TICKETS_EVENT = 'UPDATE_TICKETS_EVENT';
export const DELETE_TICKETS_EVENT = 'DELETE_TICKETS_EVENT';
export const FETCH_TICKETS_EVENT = 'FETCH_TICKETS_EVENT';
export const ERROR_TICKETS_EVENT = 'ERROR_TICKETS_EVENT';
