export const CREATE_TICKETS_CART_ITEM = 'CREATE_TICKETS_CART_ITEM';
export const READ_TICKETS_CART_ITEM = 'READ_TICKETS_CART_ITEM';
export const UPDATE_TICKETS_CART_ITEM = 'UPDATE_TICKETS_CART_ITEM';
export const DELETE_TICKETS_CART_ITEM = 'DELETE_TICKETS_CART_ITEM';
export const FETCH_TICKETS_CART_ITEM = 'FETCH_TICKETS_CART_ITEM';
export const ERROR_TICKETS_CART_ITEM = 'ERROR_TICKETS_CART_ITEM';
