export const CREATE_TICKETS_CART = 'CREATE_TICKETS_CART';
export const READ_TICKETS_CART = 'READ_TICKETS_CART';
export const UPDATE_TICKETS_CART = 'UPDATE_TICKETS_CART';
export const DELETE_TICKETS_CART = 'DELETE_TICKETS_CART';
export const FETCH_TICKETS_CART = 'FETCH_TICKETS_CART';
export const ERROR_TICKETS_CART = 'ERROR_TICKETS_CART';
