export const CREATE_TICKETS_SALE = 'CREATE_TICKETS_SALE';
export const READ_TICKETS_SALE = 'READ_TICKETS_SALE';
export const UPDATE_TICKETS_SALE = 'UPDATE_TICKETS_SALE';
export const DELETE_TICKETS_SALE = 'DELETE_TICKETS_SALE';
export const FETCH_TICKETS_SALE = 'FETCH_TICKETS_SALE';
export const ERROR_TICKETS_SALE = 'ERROR_TICKETS_SALE';
