export const CREATE_TICKETS_PROMOTER = 'CREATE_TICKETS_PROMOTER';
export const READ_TICKETS_PROMOTER = 'READ_TICKETS_PROMOTER';
export const UPDATE_TICKETS_PROMOTER = 'UPDATE_TICKETS_PROMOTER';
export const DELETE_TICKETS_PROMOTER = 'DELETE_TICKETS_PROMOTER';
export const FETCH_TICKETS_PROMOTER = 'FETCH_TICKETS_PROMOTER';
export const ERROR_TICKETS_PROMOTER = 'ERROR_TICKETS_PROMOTER';
