export const CREATE_TICKETS_COUPON = 'CREATE_TICKETS_COUPON';
export const READ_TICKETS_COUPON = 'READ_TICKETS_COUPON';
export const UPDATE_TICKETS_COUPON = 'UPDATE_TICKETS_COUPON';
export const DELETE_TICKETS_COUPON = 'DELETE_TICKETS_COUPON';
export const FETCH_TICKETS_COUPON = 'FETCH_TICKETS_COUPON';
export const ERROR_TICKETS_COUPON = 'ERROR_TICKETS_COUPON';
