export const CREATE_TICKETS_TICKET = 'CREATE_TICKETS_TICKET';
export const READ_TICKETS_TICKET = 'READ_TICKETS_TICKET';
export const UPDATE_TICKETS_TICKET = 'UPDATE_TICKETS_TICKET';
export const DELETE_TICKETS_TICKET = 'DELETE_TICKETS_TICKET';
export const FETCH_TICKETS_TICKET = 'FETCH_TICKETS_TICKET';
export const ERROR_TICKETS_TICKET = 'ERROR_TICKETS_TICKET';
